#!/bin/bash
echo "=-=-=-=-= Pushing Images =-=-=-=-="
docker buildx build \
  --push \
  --platform linux/arm64,linux/amd64 \
  --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
  --build-arg VERSION="$(xargs <VERSION)" \
  --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
  --build-arg ARCH=${ARCH} \
  --tag "${IMAGE_NAME}" .
